### ISSUE TITLE
bbands

### ISSUE THREAD

**Issue by ben211887** [10mohi6/oanda-bot-python#1]
Goodmorning,

My name is Benjamin, Thanks for this wonderful code, it works nicely! I'm having issues with implementing the bbands into the strategy. How can I for instance do a self.buy_entry when the price moves under the lower band? I figured it must be something like

`self.buy_entry = self.df.C < mean - (std * band)`

 I found: 

`return mean + (std * band), mean, mean - (std * band)`

I assume these are the three lines (upper band, mean and lowerband), but I can't figure out how to call these in the backtest or run?

Can you help? Thanks!

Benjamin

**Comment by 10mohi6** [comment]
For example, you could write
```python
def strategy(self):
    rsi = self.rsi(period=8)
    upper, mid, lower = self.bbands(period=8, band=1)
    self.sell_exit = self.buy_entry = (rsi < 20) & (self.df.C < lower)
    self.buy_exit = self.sell_entry = (rsi > 80) & (self.df.C > upper)
```

**Comment by ben211887** [comment]
Ah yes, I see, thanks! I'm fairly new to python, so thanks! Two more questions. 

1. When I backtest I presume the stop loss number in the report is the amount of times the stop loss was used?
2. No matter what settings I use, there always seems to be 1 trade with a very high drawdown (above 1000), so I get something like this:

![report](https://user-images.githubusercontent.com/69517999/92208792-34fc3f00-ee8c-11ea-925e-46a6d02924cd.png)

This seems impossible since I use the stop loss, am I right?

**Comment by 10mohi6** [comment]
1. Yes, the stop loss number.
2. It depends on which strategy you use and where you place your stop loss.

**Comment by ben211887** [comment]
Thanks!
